v2dl3-vegas CI/CD update

diff --git a/.github/workflows/v2dl3-vegas.yml b/.github/workflows/v2dl3-vegas.yml
--- a/.github/workflows/v2dl3-vegas.yml
+++ b/.github/workflows/v2dl3-vegas.yml
@@ -2,9 +2,6 @@ name: v2dl3-vegas-CI
 
 # Controls when the workflow will run
 on:
-  # push:
-  #   branches: [ "main" ]
-  # Triggers the workflow on push or pull request events but only for the "main" branch
   pull_request :
     branches: [ "main" ]
     paths:
@@ -21,7 +18,10 @@ jobs:
   v2dl3-vegas:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
+    # Environment vars for the runner
     env:
+      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
       DOCKER_IMAGE: veritasacc/vegas:v2dl3-CI
       # New 'test' outputs
       NEW_DIR: ./new-fits
@@ -31,33 +31,65 @@ jobs:
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
+      - name: Checkout new branch
+        uses: actions/checkout@v3
 
-      #- name: flake8
+      - name: flake8 formatting
+        shell: bash -leo pipefail {0}
+        run: |
+          pip install flake8
+          flake8 --count --select=E9,F63,F7,F82 --ignore=E203,W503 \
+                   --show-source --statistics .
+          flake8 --count --max-complexity=25 --ignore=E203,W503 \
+                 --max-line-length=127 --statistics .
 
-      # Runs a single command using the runners shell
+      - name: pytest
+        shell: bash -leo pipefail {0}
+        env:
+        run: |
+          pip install pytest
+          pytest .
+
       - name: Pull docker image
         run: |
-          docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
+          docker login --username=$DOCKER_USERNAME --password=$DOCKER_TOKEN
           docker pull $DOCKER_IMAGE
 
+      # Runs "utils/vegas_docker_test.runs.sh" within the docker image.
+      # First copies out the test scripts from the new branch so that they aren't overwritten by the main branch pull
       - name: Install new branch and generate .fits outputs
         run: |
-          docker run -p 80:80 -v $GITHUB_WORKSPACE:/V2DL3 $DOCKER_IMAGE /bin/bash -c \
-          "cd V2DL3 && bash utils/vegas_docker_test_runs.sh OUTDIR=$NEW_DIR"
+          cp utils/vegas_docker_test_runs.sh ../vegas_docker_test_runs_static.sh
+          cp utils/compare_fits_dirs.sh ../compare_fits_dirs.sh
+          docker run -p 80:80 -v $GITHUB_WORKSPACE:/V2DL3 $DOCKER_IMAGE /bin/bash -c "\
+          cd V2DL3 \
+          && bash utils/vegas_docker_test_runs.sh OUTDIR=$NEW_DIR \
+          "
+          cp -r $NEW_DIR ../$NEW_DIR
+          sudo rm -rf $GITHUB_WORKSPACE/*
+
+      - name: Checkout main branch
+        uses: actions/checkout@v3
+        with:
+          ref: main
 
       - name: Install main branch and generate control outputs
-        if: success() || failure()
         run: |
-          docker run -p 80:80 -v $GITHUB_WORKSPACE:/V2DL3 $DOCKER_IMAGE /bin/bash -c \
-          "cd V2DL3 && git checkout -t origin/main && pip install . && bash utils/vegas_docker_test_runs.sh OUTDIR=$CONTROL_DIR"
+          cp ../vegas_docker_test_runs_static.sh utils/vegas_docker_test_runs_static.sh
+          docker run -p 80:80 -v $GITHUB_WORKSPACE:/V2DL3 $DOCKER_IMAGE /bin/bash -c "\
+          cd V2DL3 \
+          && bash utils/vegas_docker_test_runs_static.sh OUTDIR=$CONTROL_DIR \
+          "
+          cp -r $CONTROL_DIR ../$CONTROL_DIR
 
       - name: Install fitsdiff
         run: |
           sudo apt-get install -qq astropy-utils
 
+      # A failure on this test simply means that at least one fits from the test batteries
+      # was different between the new branch and the main branch.
+      #
+      # Check the github workflow output to account for any intended differences.
       - name: Compare fits outputs
         run: |
-          sudo chown -R 777 $NEW_DIR
-          sudo chown -R 777 $CONTROL_DIR
-          bash utils/compare_fits_dirs.sh $NEW_DIR $CONTROL_DIR
+          bash ../compare_fits_dirs.sh ../$NEW_DIR ../$CONTROL_DIR
